version: '3'

services:
  db:
    image: postgres
    container_name: psql
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  web:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"